image:
  tag: v0.1.3

replicas: 1

service:
  type: NodePort
  nodePort: 30001
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    cert-manage.io/acme-challenge-type: http01
#    kubernetes.io/ingress.class: nginx
  host: shop.158.160.47.10.sslip.io