apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: web
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: knightlyflo/otus-kuber-2022-12:kubernetes-intro
          livenessProbe:
            tcpSocket: { port: 8000 }
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8000
          volumeMounts:
            - mountPath: /app
              name: app
      initContainers:
        - name: init-index
          image: busybox:1.31.0
          command: ["sh", "-c", "wget -O- https://tinyurl.com/otus-k8s-intro | sh"]
          volumeMounts:
            - mountPath: /app
              name: app
      volumes:
        - name: app
          emptyDir: {}
