apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  default.conf: |
    server {
      listen 80;
      server_name localhost;
      
      location /basic_status {
        stub_status;
        allow 127.0.0.1;
        deny all;
        }
      }