apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-monitor
  namespace: monitoring
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: nginx-metrics
  endpoints:
  - interval: 5s
    path: /metrics
    port: nginxmon
  namespaceSelector:
    matchNames:
    - default
