apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deploy
  template:
    metadata:
      labels:
        app: nginx-deploy
    spec:
      volumes:
        - name: nginx-conf
          configMap:
            name: nginx-configmap
            items:
              - key: default.conf # link from ConfigMap
                path: default.conf # where to mount inside mountPath
      containers:
      - name: nginx-server
        image: nginx
        resources: {}
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /etc/nginx/conf.d
            name: nginx-conf
            readOnly: true
      - name: exporter
        image: nginx/nginx-prometheus-exporter
        args:
          - '-nginx.scrape-uri=http://localhost/basic_status'
        ports:
          - containerPort: 9113
        resources: {}
